### ISSUE TITLE
Support for mp4 / jpg slideshows

### ISSUE THREAD

**Issue by qbdumont** [jsguy/marble#1]
Just curious if you plan on expanding this codebase to include support for both images and videos in a slideshow. I know three.js supports it, but I've found it difficult to integrate into existing code, any tips?

Thanks!

**Comment by jsguy** [comment]
There are no plans to do that - this is a viewer for 360 images only - it happens to have (very limited) support for 360 image slideshows, but I'm not looking to extend it to add video/jpg support.

You could in theory write a plugin for a different slideshow script to support 360 images, using marble through.
