### ISSUE TITLE
How to put a hyperlink into an image

### ISSUE THREAD

**Issue by voivoikeri** [jsguy/marble#2]
Dear jsguy

Thank you for bring this to us. I found this lib and it is useful for me,

Could you please share me how to put a hyper link to an image in the slide show.
I want to put a hyperlink and I can click it when sliding.

I have a garden and about 4 images of four small houses of the garden.
I want to add hyperlink for every house so when user click to a house, I will display a slide show of all images of a housse.
Is it possible?

Thank you and Best Regards,

**Comment by jsguy** [comment]
Hi voivoikeri,

There's a parameter you can pass in when initialising the slideshow:

slideshowindex - what slide to start on (0-indexed), default is 0

Just read the parameter from the url, and set it.
